TestSamJabinaJB/Models/FizzBuzzModel.cs
namespace TestSamJabinaJB.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The view model for the Fizz Buzz Operation
    /// </summary>
    /// <summary>
    /// Gets or sets the input number.
    /// </summary>
    public class FizzBuzzModel
    {
        [Required]
        [Range(1, 200)]
        public Int32 Limit
        {
            get;
            set;
        }
    }
}

TestSamJabinaJB/Controllers/FizzBuzzController.cs
namespace TestSamJabinaJB.Controllers
{
    using PagedList;
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Web.Mvc;
    using TestSamJabinaJB.BusinessLogic;
    using TestSamJabinaJB.Models;

    [HandleError]
    public class FizzBuzzController : Controller
    {
        private IFizzBuzz _fbuzz;
        private IFormatHandler _formathandler;

        /// <summary>
        /// Initialize new instance of FizzBuzzController
        /// </summary>

        public FizzBuzzController(IFizzBuzz fbuzz, IFormatHandler formathandler)
        {
            _fbuzz = fbuzz;
            _formathandler = formathandler;
        }

        /// <summary>
        /// Action method to render the initial view.
        /// </summary>
        /// <returns>Index View</returns>
        [HttpGet]
        public ViewResult Index()
        {
            return View("Index");
        }

        /// <summary>
        /// Action method to render Data button submit.
        /// </summary>
        /// <returns>FizzBuzzView View</returns>
        public ActionResult GenerateOutput(int? page, FizzBuzzModel PostModel)
        {
            // FizzBuzzModel objData = new FizzBuzzModel() { Limit = PostModel.Limit };
            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["itemPerPage"]);

            int pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            IEnumerable<string> output = new List<string>();
            IEnumerable<string> formattedoutput = new List<string>();
            ViewResult obj = new ViewResult();

            var oneToLimit = Enumerable.Range(1, PostModel.Limit);
            output = _fbuzz.Process(oneToLimit);

            if (_formathandler.IsDayToFormat())
                output = _formathandler.FormatWednesDay(output);

            return View("GenerateOutput", output.ToPagedList(page ?? 1, pageSize));
        }
    }
}

TestSamJabinaJB/Views/FizzBuzz/GenerateOutput.cshtml
@model PagedList.IPagedList<string>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "GenerateOutput";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GenerateOutput</h2>
@using (Html.BeginForm("GenerateOutput", "FizzBuzz", FormMethod.Get))
{
    <div>
        <table class="table" id="contentData">
            <tbody>
                @foreach (var element in Model)
                {

                    <tr>
                        <td colspan="2">

                            @if (@Html.DisplayFor(m => element).ToString().Equals("Fizz"))
                            {
                                <div style="color: blue">@Html.DisplayFor(m => element)</div>

                            }
                            else if (@Html.DisplayFor(m => element).ToString().Equals("Buzz"))
                            {
                                <div style="color: green">@Html.DisplayFor(m => element)</div>

                            }
                            else
                            {
                                <div>@Html.DisplayFor(m => element)</div>

                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="pagedList">
        @Html.PagedListPager(Model, page => Url.Action("GenerateOutput", new RouteValueDictionary(){ {"Page", page },

}),
PagedListRenderOptions.PageNumbersOnly)
    </div>
}

@section Script
{
    @Scripts.Render("~/bundles/jqueryval")

}

TestSamJabinaJB/Views/FizzBuzz/Index.cshtml
@model TestSamJabinaJB.Models.FizzBuzzModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@using (Html.BeginForm("GenerateOutput", "FizzBuzz"))
{
    @Html.ValidationSummary(true)

    <fieldset>

        <table>
            <tr>
                <td>
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Limit)
                    </div>
                </td>
                <td>
                    <div class="editor-field">
                        @Html.TextBoxFor(model => model.Limit)
                        @Html.ValidationMessageFor(model => model.Limit)
                    </div>
                </td>
                <td>
                    <input type="submit" name="DisplayList" value="Display List" /></td>
            </tr>
        </table>
    </fieldset>
}

@section Script {
    @Scripts.Render("~/bundles/jqueryval")
}

TestSamJabinaJB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("script", required: false)
</body>
</html>